Ci: Symfony mysql

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -8,8 +8,8 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        operating-system: [ubuntu-latest, windows-latest]
-        php-versions: ['7.3', '7.4']
+        operating-system: [ubuntu-latest]
+        php-versions: ['7.4']
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -34,5 +34,12 @@ jobs:
         run: |
           composer require symfony/orm-pack
           composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
+
+      - name: Run Migration
+        run: |
+            php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
+            php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+        env:
+            DATABASE_URL: mysql://root:@127.0.0.1:3306/blog
       - name: Run Tests
         run: php bin/phpunit --coverage-text
