Ci: run migration

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -50,14 +50,17 @@ jobs:
         run: |
           composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
 
-      - name: Run Migration
+      - name: Install ORM
         run: |
           composer require symfony/orm-pack
-          php bin/console doctrine:database:create
-          php bin/console doctrine:migrations:migrate -n || echo "No migrations found or migration failed"
-          php bin/console doctrine:fixtures:load -n
         env:
           DATABASE_URL: mysql://root:root@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/blog
+
+      - name: Run Migration
+          run: |
+            php bin/console doctrine:database:create
+            php bin/console doctrine:migrations:migrate -n || echo "No migrations found or migration failed"
+            php bin/console doctrine:fixtures:load -n
 
       - name: Run Tests
         run: php bin/phpunit --coverage-text
