Ci: Mysql cmd no interaction

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -54,9 +54,11 @@ jobs:
         run: |
           composer require symfony/orm-pack
           php bin/console doctrine:database:create
-          php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+          php bin/console doctrine:migrations:migrate -n || echo "No migrations found or migration failed"
         env:
           DATABASE_URL: mysql://root:@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/blog
+        with:
+            args: -v
 
       - name: Run Tests
         run: php bin/phpunit --coverage-text
